openapi: 3.0.3
info:
  title: User Management API
  description: API for user registration, login, logout, deletion, and permission management.
  version: 1.0.0

servers:
- url: http://api.rt.lan/
  description: Serveur principal
- url: http://user:5000
  description: Serveur docker

tags:
- name: user
  description: User management operations
- name: Permission
  description: Permission management operations

paths:
  /register:
    post:
      tags:
      - user
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: User successfully created
          content:
            application/json:
              example:
                message: "User added"
                data:
                  last_name: "Doe"
                  first_name: "John"
                  email: "john.doe@example.com"
                  password: "securepassword123"
                  birth_date: "01-01-1990"
        '400':
          description: Missing field
          content:
            application/json:
              example:
                error: "Missing field : last_name"
        '409':
          description: A user with this e-mail address already exists
          content:
            application/json:
              example:
                message: "A user with this e-mail address already exists"
        '415':
          description: Invalid content type, JSON is expected
          content:
            application/json:
              example:
                error: "Invalid content type, JSON is expected"

  /login:
    post:
      tags:
      - user
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              example:
                message: "User successfully authenticated"
        '400':
          description: Missing field
          content:
            application/json:
              example:
                error: "Missing field : email"
        '401':
          description: Incorrect password
          content:
            application/json:
              example:
                error: "Incorrect password"
        '404':
          description: User not found
          content:
            application/json:
              example:
                error: "User not found"
        '415':
          description: Invalid content type, JSON is expected
          content:
            application/json:
              example:
                error: "Invalid content type, JSON is expected"

  /user/{email}:
    get:
      tags:
      - user
      summary: User info
      parameters:
      - in: path
        name: email
        required: true
        schema:
          type: string
          example: "john.doe2@example.com"
        description: User email
      responses:
        '200':
          description: User found
          content:
            application/json:
              example:
                message: "User found"
                data:
                  last_name: "Doe"
                  first_name: "John"
                  email: "john.doe@example.com"
                  birth_date: "01-01-1990"
        '409':
          description: User not found
          content:
            application/json:
              example:
                error: "User not found"

  /modify:
    put:
      tags:
      - user
      summary: Modify user information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: User information updated
          content:
            application/json:
              example:
                message: "User modified"
                data:
                  last_name: "Doe"
                  first_name: "John"
                  email: "john.doe@example.com"
                  password: "securepassword123"
                  birth_date: "01-01-1990"
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "All fields are required"
        '409':
          description: User does not exist
          content:
            application/json:
              example:
                message: "User does not exist"

  /delete-user/{email}:
    delete:
      tags:
      - user
      summary: Delete a user
      parameters:
      - in: path
        name: email
        required: true
        schema:
          type: string
          format: email
          example: "john.doe@example.com"
        description: Email address of the user to be deleted
      responses:
        '200':
          description: User successfully deleted
          content:
            application/json:
              example:
                message: "User deleted"
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "Missing field"

  /add-permissions:
    post:
      tags:
      - Permission
      summary: Add user permissions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Permission"
      responses:
        '200':
          description: Permissions successfully added
          content:
            application/json:
              example:
                message: "Permissions added successfully"
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "Missing field : project_id"
        '404':
          description: User not found
          content:
            application/json:
              example:
                error: "User not found"
        '409':
          description: Permissions already exist
          content:
            application/json:
              example:
                error: "Permissions already exist for this user and project"

  /modify-permissions:
    put:
      tags:
      - Permission
      summary: Modify user permissions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Permission"
      responses:
        '200':
          description: Permissions successfully updated
          content:
            application/json:
              example:
                message: "Permissions updated successfully"
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "Missing field : project_id"
        '404':
          description: Permissions not found
          content:
            application/json:
              example:
                error: "Permissions not found for this user and project"

  /delete-permissions:
    delete:
      tags:
      - Permission
      summary: Delete user permissions
      parameters:
      - in: query
        name: project_id
        required: true
        schema:
          type: string
          example: "1"
        description: Project ID for which permissions should be deleted
      - in: query
        name: email
        required: true
        schema:
          type: string
          format: email
          example: "john.doe@example.com"
        description: Email address of the user whose permissions should be deleted
      responses:
        '200':
          description: Permissions successfully deleted
          content:
            application/json:
              example:
                message: "Permissions deleted successfully"
                data: "true"
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "All fields are required"
        '404':
          description: User or permissions not found
          content:
            application/json:
              example:
                error: "User or permissions not found"

  /permissions-by-project/{project_id}:
    get:
      tags:
      - Permission
      summary: Retrieve user permissions by project
      parameters:
      - in: path
        name: project_id
        required: true
        schema:
          type: string
          example: "12345"
        description: Project ID
      responses:
        '200':
          description: Permissions successfully retrieved
          content:
            application/json:
              example:
                message: "Get permissions"
                data:
                - project_id: "2"
                  email: "john.doe2@example.com"
                  read: true
                  write: false
                  admin: false
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "Project ID is required"
        '409':
          description: No permissions found for this project
          content:
            application/json:
              example:
                error: "No permissions found for this project"

  /permissions-by-email/{email}:
    get:
      tags:
      - Permission
      summary: Retrieve user permissions by email
      parameters:
      - in: path
        name: email
        required: true
        schema:
          type: string
          example: "john.doe2@example.com"
        description: User email
      responses:
        '200':
          description: Permissions successfully retrieved
          content:
            application/json:
              example:
                message: "Get permissions"
                data:
                - project_id: "2"
                  email: "john.doe2@example.com"
                  read: true
                  write: false
                  admin: false
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                error: "Email is required"
        '409':
          description: No permissions found for this user
          content:
            application/json:
              example:
                error: "No permissions found for this user"

components:
  schemas:
    User:
      type: object
      properties:
        last_name:
          type: string
          example: "Doe"
        first_name:
          type: string
          example: "John"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        password:
          type: string
          example: "securepassword123"
        birth_date:
          type: string
          format: date
          example: "01-01-1990"
      required:
      - last_name
      - first_name
      - email
      - password
      - birth_date

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        password:
          type: string
          example: "securepassword123"
      required:
      - email
      - password

    Permission:
      type: object
      properties:
        project_id:
          type: string
          example: "1"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        write:
          type: boolean
          example: true
        read:
          type: boolean
          example: true
        admin:
          type: boolean
          example: false
      required:
      - project_id
      - email
      - write
      - read
      - admin
